Document: git-squishy
Title: Debian git-squishy Manual
Author: <insert document author here>
Abstract: This manual describes what git-squishy is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/git-squishy/git-squishy.sgml.gz

Format: postscript
Files: /usr/share/doc/git-squishy/git-squishy.ps.gz

Format: text
Files: /usr/share/doc/git-squishy/git-squishy.text.gz

Format: HTML
Index: /usr/share/doc/git-squishy/html/index.html
Files: /usr/share/doc/git-squishy/html/*.html
